### PR TITLE
Replace platform-intrinsic  with core_intrinsics

### LINKED ISSUE #558: Compile Error on nightly, platform_intrinsics - feature has been removed
on `main` branch for `1.78.0-nightly (c475e2303 2024-02-28)`

```
error[E0557]: feature has been removed
  --> /home/REDACTED/.cargo/git/checkouts/pathfinder-f0bd20e7aa700f92/cb4eb59/simd/src/lib.rs:11:61
   |
   | ...intrinsics, platform_intrinsics))]
   |                ^^^^^^^^^^^^^^^^^^^ feature has been removed
   |
   = note: SIMD intrinsics use the regular intrinsics ABI now

For more information about this error, try `rustc --explain E0557`.
```

related to: https://github.com/servo/pathfinder/issues/550 and https://github.com/servo/pathfinder/pull/548

### PR DESCRIPTION
**Pull request by sagudev**
Make pathfinder_simd work on latest nightly.

Fixes #558

### CODE REVIEW

**Review by s3bk — APPROVED** [review]

**Comment by fredizzimo** [comment]
Unfortunately, this broke the build on non-nightly Arm64 builds, since `std::intrinsics::simd` is a nightly only feature.
https://doc.rust-lang.org/std/intrinsics/simd/index.html

0.5.2 of `pathfinder_simd` works fine.

**Comment by sagudev** [comment]
> Unfortunately, this broke the build on non-nightly Arm64 builds, since `std::intrinsics::simd` is a nightly only feature.

All `std::intrinsics::simd` usage is hidden behind `pf_rustc_nightly`, so it should still compile.

**Comment by fredizzimo** [comment]
Then I'm not sure what's going on, because `use std::intrinsics::simd::*;` in  `simd/src/arm/mod.rs` is included. And it's causing the following error in our CI
```
error[E0432]: unresolved import `std::intrinsics::simd`
  --> /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pathfinder_simd-0.5.3/src/arm/mod.rs:13:22
   |
13 | use std::intrinsics::simd::*;
   |                      ^^^^ could not find `simd` in `intrinsics`
```

https://github.com/neovide/neovide/actions/runs/10007814471/job/27663280524

And downgrading to 0.5.2 of `pathfinder_simd` fixed the issue (this commit) https://github.com/neovide/neovide/pull/2719/commits/89448f5d6a33412a703e98f8fb1e91275658b332

Unfortunately, I don't have a mac and I did not manage to easily setup cross compilation for ARM (neither linux or `apple-darwin` on my Linux machine, so I'm not able to reproduce the issue by compiling this repository alone. I can probably make it to work but it requires some more effort.

**Comment by sagudev** [comment]
https://github.com/neovide/neovide/actions/runs/10007814471/job/27663280524#step:3:78:
> note that the toolchain 'nightly-2023-09-30-x86_64-apple-darwin' is currently in use (overridden by '/Users/runner/work/neovide/neovide/rust-toolchain.toml'

So actually CI uses nightly and the problem is it uses too old nightly version.

**Comment by fredizzimo** [comment]
Thanks. I thought I had deleted the `rust-toolchain.toml` file a long time ago, but it must have come back with some rebase or merge. Sorry for the false report.

**Pull request merged**
