### PR TITLE
bump simd to 0.5.3 in order push fixes for stdsimd feature upstream

### PR DESCRIPTION
**Pull request by jonaspleyer**
This is a follow-up of #548 to push simd upstream.

### CODE REVIEW

**Comment by jonaspleyer** [comment]
@s3bk How do we proceed from here? Are there any more steps that need to be taken? Please let me know. I am looking forward for this fix in my other crates.

**Comment by jonaspleyer** [comment]
Tbh I did not know that I can do that. I will be looking out for that in the future though. Thanks again!

**Comment by Maurdekye** [comment]
when will this be published to crates.io?

**Comment by atouchet** [comment]
@Maurdekye it is available now: https://crates.io/crates/pathfinder_simd/0.5.3

**Pull request merged**
