### PR TITLE
Simplify the cargo-c usage and generate the library as libpathfinder

### PR DESCRIPTION
**Pull request by lu-zero**

### CODE REVIEW

**Comment by pcwalton** [comment]
Will this make the Rust crate named `pathfinder`? I think people may expect a Rust crate named `pathfinder` to export Rust functions.

**Comment by linkmauve** [comment]
Is there any reason to use the `c/` crate from Rust in any way?  I would expect it to only ever be used to generate the C library, not be linked to Rust code, so its crate name shouldn’t matter.

**Comment by lu-zero** [comment]
This is what it produces:
``` 
❯ ls -alR /tmp/staging-pathfinder/
total 0
drwxr-xr-x   3 lu_zero  wheel   96 29 Jul 23:06 .
drwxrwxrwt  21 root     wheel  672 29 Jul 23:06 ..
drwxr-xr-x   3 lu_zero  wheel   96 29 Jul 23:06 usr

/tmp/staging-pathfinder//usr:
total 0
drwxr-xr-x  3 lu_zero  wheel   96 29 Jul 23:06 .
drwxr-xr-x  3 lu_zero  wheel   96 29 Jul 23:06 ..
drwxr-xr-x  5 lu_zero  wheel  160 29 Jul 23:06 local

/tmp/staging-pathfinder//usr/local:
total 0
drwxr-xr-x  5 lu_zero  wheel  160 29 Jul 23:06 .
drwxr-xr-x  3 lu_zero  wheel   96 29 Jul 23:06 ..
drwxr-xr-x  2 lu_zero  wheel   64 29 Jul 23:06 bin
drwxr-xr-x  3 lu_zero  wheel   96 29 Jul 23:06 include
drwxr-xr-x  7 lu_zero  wheel  224 29 Jul 23:06 lib

/tmp/staging-pathfinder//usr/local/bin:
total 0
drwxr-xr-x  2 lu_zero  wheel   64 29 Jul 23:06 .
drwxr-xr-x  5 lu_zero  wheel  160 29 Jul 23:06 ..

/tmp/staging-pathfinder//usr/local/include:
total 0
drwxr-xr-x  3 lu_zero  wheel   96 29 Jul 23:06 .
drwxr-xr-x  5 lu_zero  wheel  160 29 Jul 23:06 ..
drwxr-xr-x  3 lu_zero  wheel   96 29 Jul 23:06 pathfinder

/tmp/staging-pathfinder//usr/local/include/pathfinder:
total 32
drwxr-xr-x  3 lu_zero  wheel     96 29 Jul 23:06 .
drwxr-xr-x  3 lu_zero  wheel     96 29 Jul 23:06 ..
-rw-r--r--  1 lu_zero  wheel  15097 20 Jul 18:15 pathfinder.h

/tmp/staging-pathfinder//usr/local/lib:
total 428680
drwxr-xr-x  7 lu_zero  wheel        224 29 Jul 23:06 .
drwxr-xr-x  5 lu_zero  wheel        160 29 Jul 23:06 ..
-rwxr-xr-x  1 lu_zero  wheel   16470768 20 Jul 18:14 libpathfinder.0.1.0.dylib
lrwxr-xr-x  1 lu_zero  wheel         25 29 Jul 23:06 libpathfinder.0.dylib -> libpathfinder.0.1.0.dylib
-rw-r--r--  1 lu_zero  wheel  203009600 20 Jul 18:14 libpathfinder.a
lrwxr-xr-x  1 lu_zero  wheel         25 29 Jul 23:06 libpathfinder.dylib -> libpathfinder.0.1.0.dylib
drwxr-xr-x  3 lu_zero  wheel         96 29 Jul 23:06 pkgconfig

/tmp/staging-pathfinder//usr/local/lib/pkgconfig:
total 8
drwxr-xr-x  3 lu_zero  wheel   96 29 Jul 23:06 .
drwxr-xr-x  7 lu_zero  wheel  224 29 Jul 23:06 ..
-rw-r--r--  1 lu_zero  wheel  248 29 Jul 23:06 pathfinder.pc
```

If you want I can move `c/src/lib.rs` to `src/capi.rs` and simplify further.

**Comment by pcwalton** [comment]
Well, my concern would be uploading it to crates.io I guess.

**Comment by pcwalton** [comment]
I'll approve this for now and we can revisit if we ever want to push this to crates.io.

**Pull request merged**
