### PR TITLE
Make text rendering optional in pathfinder_canvas

### LINKED ISSUE #164: Make skribo/HarfBuzz use optional
This makes me a bit sad, but given that binary size is important for wasm especially, and since there are some use cases that don't need text at all (or if they do need it it's only for debugging), we should probably have an optional dumb Latin-only shaper.

Also, HarfBuzz is our only C dependency, and it would be nice to have some kind of Rust-only version, in case a C compiler isn't handy.

### LINKED ISSUE #208: Make FreeType optional
And with that Font-Kit.
It is a [blocker for WASM](https://github.com/servo/pathfinder/issues/155) and not everyone needs it anyway.

(The [PDF viewer](https://github.com/s3bk/pdf/blob/master/view/src/lib.rs) currently still uses FreeType, but I hope to switch it to [RustType](https://gitlab.redox-os.org/redox-os/rusttype) soon.

### PR DESCRIPTION
**Pull request by est31**
Fixes #164
Fixes #208

### CODE REVIEW

**Comment by est31** [comment]
cc @sebk this is what you wanted I think

**Comment by est31** [comment]
I've tested @s3bk 's pdf viewer with this patch and it works great.

**Comment by s3bk** [comment]
thanks!
Do you think it would be cleaner to move the text stuff into canvas/src/text.rs ?

**Comment by est31** [comment]
@s3bk yeah it's cleaner. I've pushed a commit to move the text stuff into separate files.

**Comment by pcwalton** [comment]
I generally prefix all Pathfinder features with `pf-` to avoid conflicts with other crates.

**Comment by est31** [comment]
re-r? @pcwalton

**Comment by pcwalton** [comment]
Cool, thanks!

**Pull request merged**
